### ISSUE TITLE
Auto filling WorldGuard commands not working

### ISSUE THREAD

**Issue by Jackalack7234** [EngineHub/WorldGuard#2036] opened 2023-10-08 02:29 UTC
### WorldEdit Version

7.2.16

### WorldGuard Version

7.0.9

### Platform Version

1.20.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Whenever i type a command for WorldGuard, the suggestions it gives for auto fill are just player names, not what they should be.
![image](https://github.com/EngineHub/WorldGuard/assets/147290121/50ec5fc5-d128-4b2d-af2c-9fb9fa147bad)

### Expected Behavior

The auto full command suggestion should be the correct WorldGuard command suggestions

### Reproduction Steps

I have no idea how to reproduce this

**Comment by Joo200** [comment] 2023-10-08 11:10
Duplicate of https://github.com/EngineHub/WorldGuard/issues/1875

**Closed by Joo200** 2023-10-08 11:10 UTC
Labels: status:pending, type:bug
