### ISSUE TITLE
give access to translation

### ISSUE THREAD

**Issue by livxbox5** [EngineHub/WorldGuard#2043] opened 2023-11-20 18:28 UTC
### The Problem

please give me the file of all the translations of the plugin so that we can customize the message

### A Solution

please give me the file of all the translations of the plugin so that we can customize the message

**Comment by Joo200** [comment] 2023-11-20 18:45
Duplicate of https://github.com/EngineHub/WorldGuard/issues/478

**Closed by Joo200** 2023-11-20 18:45 UTC
Labels: status:pending, type:feature-request
