### ISSUE TITLE
/god /ungod /heal and other commands

### ISSUE THREAD

**Issue by noslowd0wn** [EngineHub/WorldGuard#2068] opened 2024-03-16 17:51 UTC
### WorldEdit Version

7.2.20

### WorldGuard Version

7.0.9

### Platform Version

Purpur-1.20.4-2155

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

HOW TO DISABLE THIS COMMANDS??????????????????????????????

I just need to disable commands like /god /ungod /heal  /slay /locate /stack and /;

(I wanted to write to discord but I got banned there because I sent a sticker (thumbs down))

### Expected Behavior

I just want to disable these commands

### Reproduction Steps

1. disable 
2. these 
3. commands

### Optional WorldGuard-Report

https://paste.enginehub.org/rO35WQ5OE.report

### Anything Else?

Add this feature to configuration

**Comment by Joo200** [comment] 2024-03-16 18:44
Duplicate of https://github.com/EngineHub/WorldGuard/issues/2013

**Closed by Joo200** 2024-03-16 18:44 UTC
Labels: status:pending, type:bug
