### ISSUE TITLE
Localization file

### ISSUE THREAD

**Issue by Titanium0B** [EngineHub/WorldGuard#1985] opened 2023-02-20 08:30 UTC
### The Problem

To change the message, you need to find it in the source data, change these messages and compile the plugin (for some users, this will be a problem because not everyone knows how to do it all, but there are instructions on Google about this, but the messages are scattered over many files in the source data and you need to search for them and sometimes adjusting because of this is also often a problem for users)

### A Solution

Make a localization file where all messages (or almost all) will be so that it is possible to easily and quickly change them. I know that it will probably be important to do this because you will have to rewrite most of the code, but it is worth it

### Alternatives

Search, change messages in the code, compile.. a long time. 🕒

**Comment by JOO200** [comment] 2023-02-20 10:47
Duplicate of https://github.com/EngineHub/WorldGuard/issues/478

You can customize deny messages for actions and entry/exit with the flags, there is no need to change the source code

**Closed by JOO200** 2023-02-20 10:47 UTC
Labels: status:pending, type:feature-request

**Comment by Titanium0B** [comment] 2023-02-20 11:09
Unfortunately, there is no flag here, but a complete translation of the plugin.

After each update, the plugin has to be translated for ease of use, because server users are not only prohibited from doing anything while spawning, but also from creating their own regions, sometimes changing flags (depends on the server and its rights).
For example, the user does not know English, because of this it will be difficult to use the plugin (if he is new to the servers), also fully translated messages from different plugins make their functionality understandable, for example, half of the plugins are in English, some are in Chinese (rarely) and other languages, and the user knows only Polish (for example) so it becomes not very easy to use commands, menus, etc.

**Comment by JOO200** [comment] 2023-02-20 11:14
You can use the WorldGuard API to write your own command wrapper. The wg commands use the WG API to create and change regions.

The duplicated issue is accepted but we don't have time to make any progress on it.
