### ISSUE TITLE
RGB codes for greeting/farewell/greeting-title/farewell-title

### ISSUE THREAD

**Issue by Silvobi** [EngineHub/WorldGuard#1986] opened 2023-02-22 16:06 UTC
### The Problem

I'm unable to use RGB color codes that are avaliable in 1.16 and aboce

### A Solution

Add new placeholder &#<hex-code> for example &#82ffbc

**Comment by JOO200** [comment] 2023-02-22 16:48
Duplicate of https://github.com/EngineHub/WorldGuard/issues/1623

**Closed by JOO200** 2023-02-22 16:48 UTC
Labels: status:pending, type:feature-request
