### ISSUE TITLE
Support for unicode characters in regions names

### ISSUE THREAD

**Issue by leolnid** [EngineHub/WorldGuard#1979] opened 2023-01-06 11:35 UTC
### The Problem

There is a need to use different characters in the name of the regions.

### A Solution

Request to expand the pattern to any characters (Ideally with space support)

**Comment by me4502** [comment] 2023-01-06 11:39
WorldGuard does not have region names, it has unique identifiers for each region. These should not be used as "names". If you have a plugin that is incorrectly using this as a name, it should instead be adding a "display name" flag or similar that is handled in the way you're describing

**Comment by JOO200** [comment] 2023-01-06 12:29
duplicate of [#1918](https://github.com/EngineHub/WorldGuard/issues/1918)

**Closed by JOO200** 2023-01-06 12:29 UTC
Labels: status:pending, type:feature-request

**Comment by JOO200** [comment] 2023-01-07 14:35
Maybe you can tell them to create a custom flag for `placeholder-name`, which should be used instead.

That way there would be utf8 support and no issues with mutliple regions in the same spot.
