### ISSUE TITLE
Extend Falling Block Physics Settings to Include All Blocks

### ISSUE THREAD

**Issue by Timtendo12** [EngineHub/WorldGuard#2066] opened 2024-02-25 20:18 UTC
### The Problem

Currently, we're limited to disabling the falling physics solely for Sand and Gravel. This limitation excludes other blocks such as Concrete Powder.

### A Solution

Expand the block physics setting to encompass all falling blocks, ensuring consistency.

Currently, it looks like this:
```yml
physics:
    no-physics-gravel: true
    no-physics-sand: true
```

### Alternatives

Introducing options for additional falling blocks to provide control over their physics.

### Anything Else?

No further adjustments needed.

**Comment by Joo200** [comment] 2024-02-25 20:20
Duplicate of #1411

**Closed by Joo200** 2024-02-25 20:20 UTC
Labels: status:pending, type:feature-request
