### ISSUE TITLE
Turtle eggs

### ISSUE THREAD

**Issue by Nastroszona** [EngineHub/WorldGuard#1608] opened 2020-07-15 15:53 UTC
WorldEdit version: 7.1.0;8e55131

WorldGuard version: 7.0.2-SNAPSHOT;bf2593e

Platform version: git-Paper-374 (MC: 1.15.2) (Implementing API version 1.15.2-R9.1-SNAPSHOT)

**Describe the bug**
When player throw items on turtle's eggs they will be break down.

**To Reproduce**
1. Take some cobblestone
2. Throw it on eggs

**Expected behavior**
Turtle's eggs won't be break down.

**Screenshots**
https://zapodaj.net/39e6552585846.png.html

**Comment by wizjany** [comment] 2020-07-15 15:56
is the implication here that protection works if the player is inside the region?

**Comment by Nastroszona** [comment] 2020-07-15 16:00
No

**Comment by Nastroszona** [comment] 2020-07-15 16:07
Sorry, i don't understand problem.

**Comment by Nastroszona** [comment] 2020-07-15 16:19
I misunderstood the matter, so I do new post with other case description, please close this and reopen second issue..

**Comment by wizjany** [comment] 2020-07-15 16:21
you can edit the description if you need to clarify something

![](https://i.imgur.com/2xNQshs.png)

**Comment by Nastroszona** [comment] 2020-07-15 16:26
Okay, sorry for the confusion, I update bug describe.

**Comment by wizjany** [comment] 2020-07-15 22:37
Not sure how to reproduce this. The MC wiki does state that "... or a player or item falls onto it from a higher block, the egg breaks..."
However the code seems to show that only living entities (excluding turtles and in 1.16, bats) can break eggs. Testing in game also confirms that dropping items on turtle eggs doesn't break them. Maybe I'm missing something here?

**Comment by Nastroszona** [comment] 2020-07-16 13:46
In general, animals can also destroy eggs, which is also a problem, but breaking with items it's worse. I can record this and upload on youtube, if it necessary.

**Comment by wizjany** [comment] 2020-07-17 01:37
the trampling flag already takes care of animals and such so that shouldn't be an issue. real issue is that items did in 1.14/1.15 and no one brought it up while that was actively developed. I'm not sure if I'm currently up for making a 7.0.3-backport branch right now.

**Comment by TNTUP** [comment] 2020-07-28 09:16
I can confirm, player-trampling/mobs (only in crops section) are disabled but I couldn't find a setting related to turtle eggs. Adding a setting to disable players/mobs to break turtle eggs would be beneficial to some

**Comment by wizjany** [comment] 2020-08-14 23:08
While such a setting is entirely unrelated to the original issue here, it has been added.

Also back on topic, since I have no intention of going back to 1.15, I'm going to close this issue.

**Closed by wizjany** 2020-08-14 23:08 UTC
Labels: status:pending, type:bug
