### ISSUE TITLE
Deprecation warning for EntityKnockbackByEntityEvent in WorldGuard v7.0.11

### ISSUE THREAD

**Issue by v4r1n** [EngineHub/WorldGuard#2142] opened 2024-09-11 09:10 UTC
### WorldEdit Version

FastAsyncWorldEdit-894

### WorldGuard Version

7.0.11+068ad68

### Platform Version

paper-1.21.1-74

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [ ] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

WorldGuard v7.0.11 is triggering a warning regarding the use of a deprecated event, EntityKnockbackByEntityEvent, in the method onEntityKnockbackByEntity. This event is deprecated, and it is noted that the server's performance may be affected.

### Expected Behavior

WorldGuard should register events that are not deprecated to ensure optimal server performance and prevent unnecessary warnings in the logs.

### Reproduction Steps

1.Install WorldGuard v7.0.11 on a Minecraft server.
2.Start the server and check the console logs.
3.Observe the warning regarding the deprecated event.

### Optional WorldGuard-Report

https://paste.enginehub.org/64XVJxcXd.report

### Anything Else?

This bug may impact server performance due to the deprecated event. Consider updating the event listener to a non-deprecated event to avoid potential issues.

**Comment by aurorasmiles** [comment] 2024-09-11 09:24
Duplicate of #2141

**Closed as not planned by aurorasmiles** 2024-09-11 09:24 UTC
Labels: status:invalid, type:bug
