### ISSUE TITLE
Driving a boat into a item frame breaks it in a WorldGuard claim

### ISSUE THREAD

**Issue by TomLewis** [EngineHub/WorldGuard#1915] opened 2022-05-21 16:50 UTC
### WorldEdit Version

7.2.10

### WorldGuard Version

7.0.7

### Platform Version

PurPur 1.18.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Players can sail a boat into an item frame to break it inside a worldguard region.

https://youtu.be/xTv_IRzWdDQ

### Expected Behavior

To not break the item frame.

### Reproduction Steps

1. Have a worlguard claim with an item frame
2. Use a vanilla boat to sail into it
3. bad times.

**Comment by JOO200** [comment] 2022-05-21 16:51
Duplicate of
https://github.com/EngineHub/WorldGuard/issues/1434

**Closed by JOO200** 2022-05-21 16:51 UTC
Labels: status:pending, type:bug

**Comment by TomLewis** [comment] 2022-05-21 16:57
That was posted in 2018? That's 4 years ago?!!!!???
